export const REDUXLAYER_LAYER_CREATED = 'REDUXLAYER_LAYER_CREATED';
export const REDUXLAYER_LAYER_REMOVED = 'REDUXLAYER_LAYER_REMOVED';

export const REDUXLAYER_ADD_FEATURES = 'REDUXLAYER_ADD_FEATURES';
export const REDUXLAYER_REMOVE_FEATURES = 'REDUXLAYER_REMOVE_FEATURES';
export const REDUXLAYER_CLEAR_FEATURES = 'REDUXLAYER_CLEAR_FEATURES';
export const REDUXLAYER_SET_FILTER = 'REDUXLAYER_SET_FILTER';
export const REDUXLAYER_SET_FEATURE_PARAMS = 'REDUXLAYER_SET_FEATURE_PARAMS';
export const REDUXLAYER_SET_FEATURE_COORDS = 'REDUXLAYER_SET_FEATURE_COORDS';
export const REDUXLAYER_SET_FEATURE_PROPERTIES = 'REDUXLAYER_SET_FEATURE_PROPERTIES';
export const REDUXLAYER_MOUSE_OVER_FEATURE = 'REDUXLAYER_MOUSE_OVER_FEATURE';
export const REDUXLAYER_MOUSE_OUT_FEATURE = 'REDUXLAYER_MOUSE_OUT_FEATURE';
export const REDUXLAYER_MOUSE_DOWN_FEATURE = 'REDUXLAYER_MOUSE_DOWN_FEATURE';
export const REDUXLAYER_MOUSE_UP_FEATURE = 'REDUXLAYER_MOUSE_UP_FEATURE';
